language: python
python:
          - "3.7"
before_install:
          - mv travis_secrets.yaml secrets.yaml
          - mv travis_camera.yaml camera.yaml
          - sudo add-apt-repository -y ppa:mc3man/trusty-media
          - sudo apt-get -qq update
          - sudo apt-get install -y ffmpeg
install:
          - pip3 install homeassistant
script:
          - hass -c . --script check_config
