language: python
python:
          - "3.7"
before_install:
          - mv travis_secrets.yaml secrets.yaml
          - mv travis_camera.yaml camera.yaml
install:
          - pip3 install homeassistant
script:
          - hass -c . --script check_config
