- action:
  - data:
      brightness_pct: '5'
      entity_id: light.koridor
    service: light.turn_on
  - data:
      brightness_pct: '5'
      entity_id: light.yatak_koridor
    service: light.turn_on
  alias: koridor-gece
  condition:
  - condition: zone
    entity_id: device_tracker.akin_akin
    zone: zone.home
  id: '1518894529978'
  trigger:
  - at: '22:00'
    platform: time
- action:
  - alias: ''
    data:
      brightness_pct: '70'
      entity_id: light.salon
    service: light.turn_on
  alias: fire-play-set-lights
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  id: '1518895788260'
  trigger:
  - entity_id: media_player.amazon_fire_tv
    platform: state
    to: playing
- action:
  - data:
      brightness: '255'
      entity_id: light.salon
    service: light.turn_on
  alias: fire-play-end-show
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  id: '1519410534653'
  trigger:
  - entity_id: media_player.amazon_fire_tv
    from: playing
    platform: state
- action:
  - alias: ''
    data:
      brigtness: '255'
      entity_id: light.antre
    service: light.turn_on
  alias: eve-giriş
  condition: []
  id: '1520967725331'
  trigger:
  - entity_id: binary_sensor.window__door_sensor
    from: close
    platform: state
    to: open
