- action:
  - data:
      brightness_pct: '5'
      entity_id: light.koridor
    service: light.turn_on
  - data:
      brightness_pct: '5'
      entity_id: light.yatak_koridor
    service: light.turn_on
  alias: koridor-gece
  condition:
  - condition: zone
    entity_id: device_tracker.akin_akin
    zone: zone.home
  id: '1518894529978'
  trigger:
  - at: '22:00'
    platform: time
- action:
  - alias: ''
    data:
      brightness_pct: '70'
      entity_id:
      - light.tepe
      - light.abajur
      - light.yemek_masa
      - light.sehpa
      transation: '3'
    service: light.turn_on
  alias: fire-play-set-lights
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  id: '1518895788260'
  trigger:
  - entity_id: media_player.amazon_fire_tv
    from: idle
    platform: state
    to: play
