homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ele
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz
  # Customization file
  customize: !include customize.yaml

#Enables default configuration updates:
default_config:

#Logger
logger:
  default: info

# Cloud
cloud:

#Lovelace
lovelace:
#Enable yaml for prod
  mode: yaml

#Person
person:

#Enables stream
stream:

#Enables system health:
system_health:
  
#Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

#Enables configuration UI
config:

#HTTP settings for frontend
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:

#Using mosquitto instead of embedded broker
mqtt:
  broker: !secret mqttbroker
  username: !secret mqttusername
  password: !secret mqttpassword
  client_id: !secret mqttclientid 
  discovery: true
  discovery_prefix: homeassistant

  
#Discover some devices automatically
discovery:

#Allows you to issue voice commands from the frontend in enabled browsers
conversation:

#Enables support for tracking state changes over time
history:

#View all events in a logbook
logbook:

#Enables a map showing the location of tracked devices
map:

device_tracker:
  - platform: unifi_direct
    host: !secret unifi_host
    username: !secret unifi_user
    password: !secret unifi_password

# Track the sun
sun:
weather:
  - platform: darksky
    api_key: !secret darksky_api    
sensor:
#Weather prediction
  - platform: moon
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: last_boot
      - type: memory_use
#PiHole stats
pi_hole:
  host: !secret pi_a

#Internet speed test
fastdotcom:

#TV Unit
tplink:
  discovery: false
  switch:
    - host: !secret tp_h

#Amazon echo's
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_pass
      url: amazon.com

yeelight:
  devices: 
    192.168.1.46:
      name: Bedroom Light 

homekit:
mobile_app:

#influxdb for long time data measurement
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb
  max_retries: 3
  default_measurement: state

#home_alarm
alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarm_username
  password: !secret alarm_password

#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram_api_key
#    allowed_chat_ids:
#      - !secret akin_telegram_id
#
#notify: 
#  - name: telegram_notification
#    platform: telegram
#    chat_id: !secret akin_telegram_id

#Included files
camera: !include camera.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
