homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ele
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz
  # Customization file
  customize: !include customize.yaml

#Enables system health:
system_health:
  
# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret api
updater:

#Usinig mosquitto instead of embedded broker
mqtt:
  broker: !secret broker
  discovery: true
  discovery_prefix: homeassistant
# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

#Torrent stats
transmission:
  host: !secret transmission_host
  port: 8080
  monitored_conditions:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
    - 'paused_torrents'
    - 'total_torrents'

device_tracker:
  - platform: unifi_direct
    host: !secret unifi_host
    username: !secret unifi_user
    password: !secret unifi_password

# Track the sun
sun:
weather:
  - platform: darksky
    api_key: !secret darksky_api    
sensor:
#Internet speed test
  - platform: fastdotcom
#Weather prediction
  - platform: moon
#Sensehat sensors for living room  
  - platform: sensehat
    display_options:
      - temperature
      - humidity
      - pressure

#PiHole stats
  - platform: pi_hole

#Sonar stats
  - platform: sonarr
    api_key: !secret sonar_api_key
    host: !secret sonar_host
    urlbase: sonar
    days: 15
    
binary_sensor:
  #Noise Sensors
  - platform: ffmpeg_noise
    input: !secret salon_noise_input
    name: salon    
  - platform: ffmpeg_noise
    input: !secret dino_noise_input
    name: dino
    extra_arguments: -filter:a highpass=f=300,lowpass=f=250 -codec:a libmp3lame -ar 16000
# Text to speech
tts:
  - platform: google
# Cloud
cloud:

switch:
#TV Unit
  - platform: tplink
    host: !secret tp_h

media_player:
#Amazon echo's
  - platform: alexa
    email: !secret amazon_user
    password: !secret amazon_pass
    url: amazon.com
#Kodi
  - platform: kodi
    host: !secret fire_host 
#FireTV
  - platform: firetv
    name: FireTv
    host: !secret fire_host
    adbkey: /home/homeassistant/.android/adbkey
#Raspbee host for zigbee devices
deconz:
  host: !secret deconz_host    

homekit:
upnp:
ios:

#Included files
camera: !include camera.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
