background: var(--background-image)
resources:
  - type: module
    url: /community_plugin/weather-card/weather-card.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /local/battery-entity.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
title: OmerogluHQ
views:
  - badges: []
    cards:
      - type: picture-entity
        aspect_ratio: 50%
        camera_image: camera.dino
        entity: camera.dino
        name: Dino Camera
        show_state: false
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: 'custom:mini-graph-card'
                animate: true
                entities:
                  - entity: sensor.child_room_temperature
                    index: 0
                group: false
                name: Dino
              - type: 'custom:mini-graph-card'
                entities:
                  - entity: sensor.living_room_temperature
                    index: 0
                group: false
                name: Living Room
                animate: true
          - type: horizontal-stack
            cards:
              - type: 'custom:mini-graph-card'
                animate: true
                entities:
                  - entity: sensor.bedroom_temperature
                    index: 0
                group: false
                name: Bedroom 
              - type: 'custom:mini-graph-card'
                animate: true
                entities:
                  - entity: sensor.outside_temperature
                    index: 0
                group: false
                name: Balcony             
          - type: 'custom:mini-graph-card'
            animate: true
            entities:
              - entity: sensor.living_room_humidity
                index: 0
              - entity: sensor.child_room_humidity
                index: 1
              - entity: sensor.bedroom_humidity
                index: 2
            group: false
            name: Humidity
      - type: 'custom:weather-card'
        current: true
        details: false
        entity: weather.dark_sky
        forecast: true
        name: Weather
      - type: alarm-panel
        entity: alarm_control_panel.alarm_com
        name: Home Alarm
        states:
          - arm_home
          - arm_away
      - type: entity-filter
        entities:
          - media_player.apple_tv
          - media_player.echo_bedroom
          - entity: media_player.living_room
            type: 'custom:mini-media-player'
            artwork: cover
            hide:
              power_state: false
              source: true
              volume: false
            icon: 'mdi:spotify'
        state_filter:
          - playing
    icon: 'mdi:home'
    panel: false
    path: default_view
    title: Home
  - badges: []
    cards:
      - artwork: cover
        entity: media_player.living_room
        hide:
          power_state: false
          source: true
          volume: false
        icon: 'mdi:spotify'
        type: 'custom:mini-media-player'
      - aspect_ratio: 50%
        camera_image: camera.salon
        camera_view: live
        entity: camera.salon
        name: Living Room Camera
        show_name: true
        show_state: false
        type: picture-entity
      - entity: sensor.living_room_temperature
        graph: line
        hours_to_show: 24
        type: sensor
      - entities:
          - entity: sensor.living_room_humidity
          - entity: sensor.living_room_pressure
          - entity: switch.livingroomcam_h264_rtsp_server
          - entity: switch.salon_tv
        show_name: false
        type: glance
      - entities:
          - entity: light.ceiling_lamp
          - entity: light.table_lamp
          - entity: light.lampshade
          - entity: light.coffee_table
          - entity: switch.tv_light
        show_header_toggle: true
        title: Living Room Lights
        type: entities
    icon: 'mdi:ceiling-light'
    path: livingroom
    title: Living Room
  - badges: []
    cards:
      - entity: media_player.echo_kitchen
        type: media-control
      - entity: light.kitchen
        type: light
    icon: 'mdi:fridge'
    path: kitchen
    title: Kitchen
  - badges: []
    cards:
      - detail: 2
        entity: sensor.child_room_temperature
        graph: line
        hours_to_show: 24
        name: Temperature
        type: sensor
      - entity: sensor.child_room_humidity
        graph: line
        name: Humidity
        type: sensor
      - entity: light.child_room
        name: Dino's Light
        type: light
    icon: 'mdi:human-child'
    path: dino
    title: Dino's Room
  - badges: []
    cards:
      - entity: media_player.echo_library
        type: media-control
      - entities:
          - entity: switch.library_light
        show_icon: true
        show_name: false
        title: Library Light
        type: glance
    icon: 'mdi:library'
    panel: false
    path: library
    title: Library
  - badges: []
    cards:
      - entity: media_player.echo_bedroom
        type: media-control
      - entity: light.bedroom_light
        name: Bedroom Light
        type: light
      - entity: sensor.bedroom_temperature
        graph: line
        type: sensor
    icon: 'mdi:bed-king'
    path: bed-room
    title: 'Bed Room '
  - badges: []
    cards:
      - entity: sensor.outside_temperature
        graph: line
        type: sensor
      - entity: light.balcony
        name: Balcony Light
        type: light
      - entity: sensor.outside_humidity
        graph: line
        type: sensor
    icon: 'mdi:tree'
    path: balcony
    title: Balcony
  - badges: []
    cards:
      - entities:
          - entity: binary_sensor.main_door
          - entity: binary_sensor.closet_door
        show_icon: true
        show_state: true
        title: Doors
        type: glance
      - entities:
          - entity: light.corridor
          - entity: light.bedroom_hall
          - entity: light.doorway
        title: Lights
        type: glance
    icon: 'mdi:door'
    path: aisle
    title: Aisle
  - badges: []
    cards: []
    icon: 'mdi:earth'
    path: outside
    title: Outside
  - badges: []
    cards:
      - entities:
          - entity: sensor.fast_com_download
          - entity: sensor.pi_hole_ads_blocked_today
          - entity: sensor.pi_hole_dns_queries_today
          - entity: binary_sensor.remote_ui
        show_header_toggle: false
        title: Internet
        type: entities
      - entities:
          - entity: sensor.closet_door_battery_level
        show_header_toggle: false
        title: Batteries
        type: entities
    icon: 'mdi:wrench'
    path: tools
    resources: null
    title: Tools

