background: var(--background-image)
resources:
  - type: module
    url: /community_plugin/weather-card/weather-card.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /local/battery-entity.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
title: OmerogluHQ
views:
  - !include lovelace/view-default.yaml
  - !include lovelace/living-room.yaml
  - badges: []
    cards:
      - entity: media_player.echo_kitchen
        type: media-control
      - entity: light.kitchen
        type: light
    icon: 'mdi:fridge'
    path: kitchen
    title: Kitchen
  - badges: []
    cards:
      - detail: 2
        entity: sensor.child_room_temperature
        graph: line
        hours_to_show: 24
        name: Temperature
        type: sensor
      - entity: sensor.child_room_humidity
        graph: line
        name: Humidity
        type: sensor
      - entity: light.child_room
        name: Dino's Light
        type: light
    icon: 'mdi:human-child'
    path: dino
    title: Dino's Room
  - badges: []
    cards:
      - entity: media_player.echo_library
        type: media-control
      - entities:
          - entity: switch.library_light
        show_icon: true
        show_name: false
        title: Library Light
        type: glance
    icon: 'mdi:library'
    panel: false
    path: library
    title: Library
  - badges: []
    cards:
      - entity: media_player.echo_bedroom
        type: media-control
      - entity: light.bedroom_light
        name: Bedroom Light
        type: light
      - entity: sensor.bedroom_temperature
        graph: line
        type: sensor
    icon: 'mdi:bed-king'
    path: bed-room
    title: 'Bed Room '
  - badges: []
    cards:
      - entity: sensor.outside_temperature
        graph: line
        type: sensor
      - entity: light.balcony
        name: Balcony Light
        type: light
      - entity: sensor.outside_humidity
        graph: line
        type: sensor
    icon: 'mdi:tree'
    path: balcony
    title: Balcony
  - badges: []
    cards:
      - entities:
          - entity: binary_sensor.main_door
          - entity: binary_sensor.closet_door
        show_icon: true
        show_state: true
        title: Doors
        type: glance
      - entities:
          - entity: light.corridor
          - entity: light.bedroom_hall
          - entity: light.doorway
        title: Lights
        type: glance
    icon: 'mdi:door'
    path: aisle
    title: Aisle
  - badges: []
    cards: []
    icon: 'mdi:earth'
    path: outside
    title: Outside
  - badges: []
    cards:
      - entities:
          - entity: sensor.fast_com_download
          - entity: sensor.pi_hole_ads_blocked_today
          - entity: sensor.pi_hole_dns_queries_today
          - entity: binary_sensor.remote_ui
        show_header_toggle: false
        title: Internet
        type: entities
      - entities:
          - entity: sensor.closet_door_battery_level
        show_header_toggle: false
        title: Batteries
        type: entities
    icon: 'mdi:wrench'
    path: tools
    resources: null
    title: Tools

