title: OmerogluHQ
views:
  - badges:
      - binary_sensor.remote_ui
    cards:
      - entity: camera.livingroomcam_motion_snapshot
        type: picture-entity
      - entity: weather.dark_sky
        name: Weather
        type: weather-forecast
      - entities:
          - entity: person.akin_omeroglu
          - entity: zone.home
        type: map
    icon: 'mdi:home'
    path: default_view
    title: Home
  - badges: []
    cards:
      - entity: sensor.living_room_temperature
        graph: line
        hours_to_show: 24
        type: sensor
      - entity: media_player.echo_livingroom
        type: media-control
      - camera_view: live
        entity: camera.salon
        name: Living Room Camera
        type: picture-entity
      - entities:
          - entity: sensor.livingroom_humidity
          - entity: sensor.living_room_pressure
          - entity: switch.livingroomcam_h264_rtsp_server
          - entity: switch.salon_tv
        show_name: false
        type: glance
      - entities:
          - entity: light.ceiling_lamp
          - entity: light.table_lamp
          - entity: light.lampshade
          - entity: light.coffee_table
        show_header_toggle: false
        title: Living Room Lights
        type: entities
    icon: 'mdi:ceiling-light'
    path: livingroom
    title: Living Room
  - badges: []
    cards:
      - entity: light.kitchen
        name: Kitchen Light
        type: light
      - entity: media_player.echo_kitchen
        type: media-control
    icon: 'mdi:fridge'
    path: kitchen
    title: Kitchen
  - badges: []
    cards:
      - detail: 2
        entity: sensor.child_room_temperature
        graph: line
        hours_to_show: 24
        name: Temperature
        type: sensor
      - entity: sensor.yatak_odasi_2
        graph: line
        name: Humidity
        type: sensor
      - entity: light.child_room
        name: Dino's Light
        type: light
    icon: 'mdi:baby-buggy'
    path: dino
    title: Dino's Room
  - badges: []
    cards:
      - entity: media_player.echo_library
        type: media-control
      - entities:
          - entity: switch.library_light
        show_icon: true
        show_name: false
        title: Library Light
        type: glance
    icon: 'mdi:library'
    panel: false
    path: library
    title: Library
  - badges: []
    cards:
      - entity: sensor.outside_temperature
        graph: line
        type: sensor
      - entity: light.balcony
        name: Balcony Light
        type: light
      - entity: sensor.outside_humidity
        graph: line
        type: sensor
    icon: 'mdi:tree'
    path: balcony
    title: Balcony
  - badges: []
    cards:
      - entities:
          - entity: binary_sensor.main_door
          - entity: binary_sensor.closet_door
        show_icon: true
        show_state: true
        title: Doors
        type: glance
      - entities:
          - entity: light.corridor
          - entity: light.bedroom_hall
          - entity: light.doorway
        title: Lights
        type: glance
    icon: 'mdi:door'
    path: aisle
    title: Aisle
  - badges: []
    cards: []
    icon: 'mdi:earth'
    path: outside
    title: Outside
  - badges: []
    cards: []
    icon: 'mdi:wrench'
    path: tools
    title: Tools

